"""The slider definitions that drive the tuner form."""

from __future__ import annotations

from evals.catan_board_bench.render import DEFAULT_RENDER_STYLE

SLIDERS = [
    {
        "key": "road_width_factor",
        "label": "Road width",
        "min": 0.45,
        "max": 1.15,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.road_width_factor,
    },
    {
        "key": "road_length_factor",
        "label": "Road length",
        "min": 0.80,
        "max": 1.25,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.road_length_factor,
    },
    {
        "key": "dock_width",
        "label": "Dock width",
        "min": 2.0,
        "max": 14.0,
        "step": 0.25,
        "default": DEFAULT_RENDER_STYLE.dock_width,
    },
    {
        "key": "dock_extend_factor",
        "label": "Dock length extra",
        "min": -0.45,
        "max": 0.40,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.dock_extend_factor,
    },
    {
        "key": "dock_sand_gap",
        "label": "Dock sand gap",
        "min": 0.0,
        "max": 16.0,
        "step": 0.25,
        "default": DEFAULT_RENDER_STYLE.dock_sand_gap,
    },
    {
        "key": "dock_port_gap",
        "label": "Dock ship gap",
        "min": 0.0,
        "max": 24.0,
        "step": 0.5,
        "default": DEFAULT_RENDER_STYLE.dock_port_gap,
    },
    {
        "key": "dock_ship_clearance_factor",
        "label": "Dock ship clear",
        "min": 0.0,
        "max": 0.35,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.dock_ship_clearance_factor,
    },
    {
        "key": "coast_size_factor",
        "label": "Coast overlap",
        "min": 0.96,
        "max": 1.12,
        "step": 0.005,
        "default": DEFAULT_RENDER_STYLE.coast_size_factor,
    },
    {
        "key": "view_padding_factor",
        "label": "View padding",
        "min": 0.70,
        "max": 2.50,
        "step": 0.05,
        "default": DEFAULT_RENDER_STYLE.view_padding_factor,
    },
    {
        "key": "robber_size_factor",
        "label": "Robber size",
        "min": 0.45,
        "max": 1.20,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.robber_size_factor,
    },
    {
        "key": "settlement_size_factor",
        "label": "Settlement size",
        "min": 0.45,
        "max": 0.90,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.settlement_size_factor,
    },
    {
        "key": "settlement_y_factor",
        "label": "Settlement y offset",
        "min": 0.45,
        "max": 0.95,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.settlement_y_factor,
    },
    {
        "key": "settlement_x_offset",
        "label": "Settlement x offset",
        "min": -20.0,
        "max": 20.0,
        "step": 0.5,
        "default": DEFAULT_RENDER_STYLE.settlement_x_offset,
    },
    {
        "key": "city_size_factor",
        "label": "City size",
        "min": 0.55,
        "max": 1.10,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.city_size_factor,
    },
    {
        "key": "city_width_factor",
        "label": "City width",
        "min": 0.80,
        "max": 1.45,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.city_width_factor,
    },
    {
        "key": "city_y_factor",
        "label": "City y offset",
        "min": 0.45,
        "max": 0.95,
        "step": 0.01,
        "default": DEFAULT_RENDER_STYLE.city_y_factor,
    },
    {
        "key": "city_x_offset",
        "label": "City x offset",
        "min": -20.0,
        "max": 20.0,
        "step": 0.5,
        "default": DEFAULT_RENDER_STYLE.city_x_offset,
    },
]
