#!/usr/bin/env python3
"""Generate the Prompt Studio's shared-suite TypeScript types from the pydantic model.

``uv run --no-sync python -m scripts.gen_prompt_studio_types`` rewrites the
TypeScript file; ``--check`` exits 1 if it is stale. The Studio receives
``SharedPromptSuite.model_dump(mode="json")``, which always emits every field,
so every generated property is required.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import cast, get_args

from cle.harness.components import ComponentInput, SuiteStatus
from cle.harness.shared_suite import SharedPromptSuite

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    PROJECT_ROOT / "playground/frontend/src/components/prompts/contract/sharedPromptSuite.ts"
)
# Pydantic $defs names -> the TypeScript names the Studio already imports.
INTERFACE_NAMES = {
    "ComponentDefinition": "SharedComponentDefinition",
    "ComponentComposition": "SharedComposition",
    "SharedCompositions": "SharedCompositions",
}
ROOT_NAME = "SharedPromptDocument"
# Python Literal aliases that become named TypeScript unions instead of inline ones.
LITERAL_ALIASES: dict[tuple[str, ...], str] = {
    tuple(get_args(SuiteStatus)): "SuiteStatus",
    tuple(get_args(ComponentInput)): "ComponentInput",
}
SCALARS = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}
HEADER = (
    "// Generated by scripts/gen_prompt_studio_types.py from\n"
    "// cle.harness.shared_suite.SharedPromptSuite. Do not edit; rerun the script.\n"
)

Schema = Mapping[str, object]


def _schema(value: object) -> Schema:
    if not isinstance(value, Mapping):
        raise TypeError(f"expected a JSON-schema object, got {value!r}")
    return cast(Schema, value)


def _literal_union(values: tuple[str, ...]) -> str:
    return LITERAL_ALIASES.get(values) or " | ".join(f"'{value}'" for value in values)


def ts_type(schema: Schema) -> str:
    """Render one JSON-schema node as a TypeScript type expression."""
    if isinstance(ref := schema.get("$ref"), str):
        return INTERFACE_NAMES[ref.rsplit("/", 1)[-1]]
    if "const" in schema:
        return f"'{schema['const']}'"
    if isinstance(enum := schema.get("enum"), list):
        return _literal_union(tuple(str(value) for value in enum))
    kind = schema.get("type")
    if kind == "array":
        item = ts_type(_schema(schema["items"]))
        return f"{item}[]" if item.isidentifier() else f"({item})[]"
    if kind == "object":
        return f"Record<string, {ts_type(_schema(schema['additionalProperties']))}>"
    if isinstance(kind, str) and kind in SCALARS:
        return SCALARS[kind]
    raise ValueError(f"unsupported JSON-schema node: {dict(schema)!r}")


def _interface(name: str, schema: Schema) -> str:
    properties = _schema(schema["properties"])
    body = "".join(
        f"  {field}: {ts_type(_schema(node))};\n" for field, node in properties.items()
    )
    return f"export interface {name} {{\n{body}}}\n"


def render() -> str:
    schema = SharedPromptSuite.model_json_schema(mode="serialization")
    definitions = _schema(schema["$defs"])
    if unknown := definitions.keys() - INTERFACE_NAMES.keys():
        raise ValueError(f"name the new pydantic models in INTERFACE_NAMES: {sorted(unknown)}")
    aliases = "".join(
        f"export type {name} = {' | '.join(repr(value) for value in values)};\n"
        for values, name in LITERAL_ALIASES.items()
    )
    interfaces = [
        _interface(INTERFACE_NAMES[key], _schema(definitions[key])) for key in INTERFACE_NAMES
    ]
    return "\n".join([HEADER, aliases, *interfaces, _interface(ROOT_NAME, schema)])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != expected:
            print(f"{OUTPUT.relative_to(PROJECT_ROOT)} is stale; rerun without --check")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
