// Generated by scripts/gen_prompt_studio_types.py from
// cle.harness.shared_suite.SharedPromptSuite. Do not edit; rerun the script.

export type SuiteStatus = 'active' | 'legacy' | 'deprecated';
export type ComponentInput = 'color' | 'notes' | 'max_notes_chars' | 'visible_events' | 'recent_table_talk' | 'commitments' | 'phase_info' | 'board_state' | 'resources' | 'opponents' | 'trade_window' | 'phase_guidance' | 'legal_actions' | 'decision_request' | 'trigger';

export interface SharedComponentDefinition {
  channel: 'system' | 'environment';
  inputs: ComponentInput[];
  template: string;
  empty: 'omit' | 'include';
  empty_text: string;
}

export interface SharedComposition {
  order: string[];
  response: string;
}

export interface SharedCompositions {
  decision: SharedComposition;
  speech: SharedComposition;
}

export interface SharedPromptDocument {
  id: string;
  version: number;
  status: SuiteStatus;
  memory_mode: 'fresh_notes';
  max_notes_chars: number;
  initial_placement_order: 'omit' | 'both_rounds';
  reactive_speech: boolean;
  deterministic_batches: boolean;
  components: Record<string, SharedComponentDefinition>;
  compositions: SharedCompositions;
  phase_guidance: Record<string, string>;
}
